spring.application.name=payment-service
server.port=8085

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/payment_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:123456}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:admin}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:123456}
app.messaging.notification-exchange=${NOTIFICATION_EXCHANGE:cinema.events}
app.messaging.notification-routing-key=${NOTIFICATION_ROUTING_KEY:notification.requested}

eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
app.jwt.secret=${APP_JWT_SECRET:cinema-management-system-demo-secret-key-please-change}
app.payment.callback-secret=${PAYMENT_CALLBACK_SECRET:cinema-payment-callback-demo-secret}
springdoc.swagger-ui.path=/swagger-ui.html
